### ISSUE TITLE
Construction of pydantic models in projects.get_active_config

### ISSUE THREAD

**Issue by sebastiandixa** [humanloop/humanloop-python#66] opened 2024-01-25 14:43 UTC
Hi,

I'm moving from humanloop 0.5.x to 0.7.1 and observing weird behaviors in pydantic models construction. In 0.7.1 when fetching the active config of a project I get this:
```python
humanloop.projects.get_active_config('pr_xxx', 'staging')
GetModelConfigResponse(project_id='pr_xxx' project_name='inquiry' ...
 config=GenericConfigResponse(id='config_xxx', type='model', name='v1-gpt35-staging', description=None, other={})
 ... )
``` 
I was expecting the `config` field to be of type `ModelConfigResponse`, but I'm getting a `GenericConfigResponse`.

As a workaournd, I'm fetching the config using the `raw` namespace in order to get the data I need expecting:
```python
humanloop.projects.raw.get_active_config('pr_xxx', 'staging')
{
  "project_id":"pr_xxx",
  "project_name":"inquiry",
  ...
  "config":{
    "id":"config_xxx",
    "other":{    
    },
    "type":"model",
    "name":"v1-gpt35-staging",
    "description":"None",
    "provider":"openai_azure",
    "model":"gpt-35-turbo",
    "max_tokens":-1,
    ...,
    "chat_template":[ ... ],
    "tool_configs":[ ... ],
    "tools":[ ... ],
    "endpoint":"chat"
  }
}
```

I don't know if related but I get warnings about serialization of dates and the use of protected namespaces:
```
Field "model_config_" has conflict with protected namespace "model_".
``` 

I'm using python 3.11 and pydantic 2.4.2. Thanks :)

**Comment by dphuang2** [comment] 2024-01-25 21:03
@sebastiandixa thanks for reporting this 🙏 

I have identified a root cause and will be working on a fix shortly. We will update the Python SDK once a fix has been implemented.

**Comment by dphuang2** [comment] 2024-01-26 18:45
@sebastiandixa version `0.7.3` of the Python SDK has resolved the issue. 

Please try the new version and let me know if the issue persists or if you have any other problem!

**Comment by sebastiandixa** [comment] 2024-01-29 11:36
@dphuang2 Thanks for the fix :+1: Now I get the right data!

**Closed** 2024-01-29 16:01 UTC
